services:
  - type: web
    name: task-manager-app
    env: docker
    repo: https://github.com/zyadelmahdy/task_manager.git
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: /app:/app/task_manager_project