services:
  # A Docker web service
  - type: web
    name: task-manager-app
    env: docker
    repo: https://github.com/yourusername/task_manager.git
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    dockerCommand: bash -c "/wait-for-db.sh postgres && cd task_manager_project && python manage.py migrate && gunicorn task_manager_project.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000

  # A PostgreSQL database
  - type: postgres  # Changed from pgsql to postgres
    name: task-manager-db
    region: oregon
    plan: free
    ipAllowList: []